included:
  - local-coder
  - Sources

excluded:
  - build
  - DerivedData
  - local-coder.xcodeproj

disabled_rules:
  - closure_parameter_position
  - file_length
  - function_parameter_count
  - large_tuple
  - line_length
  - opening_brace
  - trailing_comma

cyclomatic_complexity:
  warning: 15
  error: 30
  ignores_case_statements: true
function_body_length:
  warning: 180
type_body_length:
  warning: 600

opt_in_rules:
  - empty_xctest_method
  - force_unwrapping
  - implicitly_unwrapped_optional
  - weak_delegate

analyzer_rules:
  - unused_declaration
  - unused_import
