import Foundation

public struct DataModelMarkdownRenderer: Sendable {
  public init() {}

  public func render(_ document: DataModelDocument) -> String {
    let models = document.models.sorted { lhs, rhs in
      if lhs.name == rhs.name {
        return lhs.sourcePath < rhs.sourcePath
      }
      return lhs.name < rhs.name
    }
    let knownTypes = Set(models.map(\.name))
    let relations = modelRelations(for: models, knownTypes: knownTypes)

    var lines: [String] = [
      "# LocalCoderCore Data Model",
      "",
      "Generated by `just data-model`. Do not edit this file by hand.",
      "",
      "## Overview",
      "",
      "```mermaid",
      "%%{init: {\"themeVariables\": {\"fontSize\": \"18px\"}, \"flowchart\": {\"nodeSpacing\": 60, \"rankSpacing\": 80}}}%%",
      "flowchart TD",
    ]

    if relations.isEmpty {
      lines.append("  Empty[\"No model relations found\"]")
    } else {
      lines.append(
        contentsOf: relations.map { relation in
          let edge = relation.kind == .derived ? "-. derives .->" : "-->"
          return "  \(mermaidID(relation.source)) \(edge) \(mermaidID(relation.target))"
        }
      )
    }

    lines.append("```")
    lines.append("")
    lines.append("## Models")
    lines.append("")

    for model in models {
      lines.append("### \(model.name)")
      lines.append("")
      lines.append("- Kind: `\(model.kind.rawValue)`")
      lines.append("- Source: `\(model.sourcePath)`")
      if !model.conformances.isEmpty {
        lines.append(
          "- Conforms to: \(model.conformances.map { "`\($0)`" }.joined(separator: ", "))")
      }
      if let summary = model.summary {
        lines.append("- Summary: \(summary)")
      }
      if let aliasedType = model.aliasedType {
        lines.append("- Aliased type: `\(aliasedType)`")
      }

      if !model.properties.isEmpty {
        lines.append("")
        lines.append("Properties:")
        lines.append("")
        for property in model.properties.sorted(by: { $0.name < $1.name }) {
          lines.append("- `\(property.name): \(property.type)`")
        }
      }

      if !model.cases.isEmpty {
        lines.append("")
        lines.append("Cases:")
        lines.append("")
        for enumCase in model.cases.sorted(by: { $0.name < $1.name }) {
          lines.append("- `\(enumCase.signature)`")
        }
      }

      let outgoing =
        relations
        .filter { $0.source == model.name }
        .map(\.target)
        .sorted()
      if !outgoing.isEmpty {
        lines.append("")
        lines.append("Relations:")
        lines.append("")
        for target in outgoing {
          lines.append("- `\(target)`")
        }
      }

      lines.append("")
    }

    return lines.joined(separator: "\n")
  }

  private func modelRelations(
    for models: [DataModelDeclaration],
    knownTypes: Set<String>
  ) -> [ModelRelation] {
    var relations = Set<ModelRelation>()

    for model in models {
      for conformance in model.conformances {
        insertRelations(
          from: model.name,
          rawType: conformance,
          knownTypes: knownTypes,
          into: &relations
        )
      }
      for property in model.properties {
        insertRelations(
          from: model.name,
          rawType: property.type,
          knownTypes: knownTypes,
          into: &relations
        )
      }
      for enumCase in model.cases {
        for value in enumCase.associatedValues {
          insertRelations(
            from: model.name,
            rawType: value.type,
            knownTypes: knownTypes,
            into: &relations
          )
        }
      }
      if let aliasedType = model.aliasedType {
        insertRelations(
          from: model.name,
          rawType: aliasedType,
          knownTypes: knownTypes,
          into: &relations
        )
      }
    }

    return relations.sorted { lhs, rhs in
      if lhs.source == rhs.source {
        if lhs.target == rhs.target {
          return lhs.kind.rawValue < rhs.kind.rawValue
        }
        return lhs.target < rhs.target
      }
      return lhs.source < rhs.source
    }
  }

  private func insertRelations(
    from source: String,
    rawType: String,
    knownTypes: Set<String>,
    into relations: inout Set<ModelRelation>
  ) {
    for typeName in referencedModelTypes(in: rawType, knownTypes: knownTypes)
    where typeName != source {
      relations.insert(
        ModelRelation(
          source: source,
          target: typeName,
          kind: source.hasSuffix("Projection") ? .derived : .direct
        )
      )
    }
  }
}

public func referencedModelTypes(in rawType: String, knownTypes: Set<String>) -> [String] {
  let cleaned =
    rawType
    .replacingOccurrences(of: "any ", with: "")
    .replacingOccurrences(of: "some ", with: "")

  let tokens = cleaned.split { character in
    !(character.isLetter || character.isNumber || character == "_" || character == ".")
  }

  let references = tokens.compactMap { token -> String? in
    let normalized = token.split(separator: ".").first.map(String.init) ?? String(token)
    guard knownTypes.contains(normalized) else {
      return nil
    }
    return normalized
  }

  return Array(Set(references)).sorted()
}

private struct ModelRelation: Hashable {
  enum Kind: String {
    case direct
    case derived
  }

  var source: String
  var target: String
  var kind: Kind
}

extension DataModelCase {
  fileprivate var signature: String {
    guard !associatedValues.isEmpty else {
      return name
    }

    let values = associatedValues.map { value in
      if let label = value.label {
        return "\(label): \(value.type)"
      }
      return value.type
    }
    .joined(separator: ", ")
    return "\(name)(\(values))"
  }
}

private func mermaidID(_ name: String) -> String {
  name.replacingOccurrences(of: ".", with: "_")
}
