import Testing

@testable import DataModelGenerator

struct DataModelMarkdownRendererTests {
  @Test
  func rendererProducesDeterministicMarkdownWithRelations() {
    let document = DataModelDocument(
      models: [
        DataModelDeclaration(
          name: "ToolResultPayload",
          kind: .enum,
          cases: [
            DataModelCase(
              name: "readFile",
              associatedValues: [DataModelAssociatedValue(type: "ReadFileResult")]
            )
          ],
          sourcePath: "Sources/SumikaCore/Models/ToolCall.swift"
        ),
        DataModelDeclaration(
          name: "ChatSessionState",
          kind: .struct,
          properties: [
            DataModelProperty(name: "turns", type: "[ChatTurn]", isStored: true)
          ],
          sourcePath: "Sources/SumikaCore/Models/ChatSessionState.swift"
        ),
        DataModelDeclaration(
          name: "ChatTurn",
          kind: .struct,
          properties: [
            DataModelProperty(name: "items", type: "[ChatTurnItem]", isStored: true)
          ],
          sourcePath: "Sources/SumikaCore/Models/ChatTurn.swift"
        ),
        DataModelDeclaration(
          name: "ChatTurnItem",
          kind: .enum,
          cases: [
            DataModelCase(
              name: "tool",
              associatedValues: [DataModelAssociatedValue(type: "ToolCallRecord")]
            )
          ],
          sourcePath: "Sources/SumikaCore/Models/ChatTurn.swift"
        ),
        DataModelDeclaration(
          name: "ReadFileResult",
          kind: .enum,
          sourcePath: "Sources/SumikaCore/Models/ToolCall.swift"
        ),
        DataModelDeclaration(
          name: "ToolCallRecord",
          kind: .struct,
          properties: [
            DataModelProperty(name: "resultPayload", type: "ToolResultPayload?", isStored: true)
          ],
          sourcePath: "Sources/SumikaCore/Models/ToolCall.swift"
        ),
      ]
    )

    let markdown = DataModelMarkdownRenderer().render(document)

    #expect(markdown.contains("# SumikaCore Data Model"))
    #expect(markdown.contains("Generated by `just data-model`. Do not edit this file by hand."))
    #expect(markdown.contains("\"fontSize\": \"18px\""))
    #expect(markdown.contains("\"nodeSpacing\": 60"))
    #expect(markdown.contains("flowchart TD"))
    #expect(markdown.contains("  ChatSessionState --> ChatTurn"))
    #expect(markdown.contains("  ChatTurn --> ChatTurnItem"))
    #expect(markdown.contains("  ChatTurnItem --> ToolCallRecord"))
    #expect(markdown.contains("  ToolCallRecord --> ToolResultPayload"))
    #expect(markdown.contains("  ToolResultPayload --> ReadFileResult"))
    #expect(markdown.contains("### ChatSessionState"))
    #expect(markdown.contains("- `turns: [ChatTurn]`"))
    #expect(markdown.contains("- `items: [ChatTurnItem]`"))
    #expect(markdown.contains("- `readFile(ReadFileResult)`"))
  }
}
