import Testing

@testable import DataModelGeneratorCore

struct DataModelMarkdownRendererTests {
  @Test
  func rendererProducesDeterministicMarkdownWithRelations() {
    let document = DataModelDocument(
      models: [
        DataModelDeclaration(
          name: "ToolResultPayload",
          kind: .enum,
          cases: [
            DataModelCase(
              name: "readFile",
              associatedValues: [DataModelAssociatedValue(type: "ReadFileResult")]
            )
          ],
          sourcePath: "Sources/LocalCoderCore/Models/ToolCall.swift"
        ),
        DataModelDeclaration(
          name: "ChatSessionState",
          kind: .struct,
          properties: [
            DataModelProperty(name: "turns", type: "[ChatTurn]", isStored: true),
            DataModelProperty(name: "toolCalls", type: "[ToolCallRecord]", isStored: true),
          ],
          sourcePath: "Sources/LocalCoderCore/Models/ChatSessionState.swift"
        ),
        DataModelDeclaration(
          name: "ChatTurn",
          kind: .struct,
          sourcePath: "Sources/LocalCoderCore/Models/ChatTurn.swift"
        ),
        DataModelDeclaration(
          name: "ReadFileResult",
          kind: .enum,
          sourcePath: "Sources/LocalCoderCore/Models/ToolCall.swift"
        ),
        DataModelDeclaration(
          name: "ToolCallRecord",
          kind: .struct,
          properties: [
            DataModelProperty(name: "resultPayload", type: "ToolResultPayload?", isStored: true)
          ],
          sourcePath: "Sources/LocalCoderCore/Models/ToolCall.swift"
        ),
      ]
    )

    let markdown = DataModelMarkdownRenderer().render(document)

    #expect(markdown.contains("# LocalCoderCore Data Model"))
    #expect(markdown.contains("Generated by `just data-model`. Do not edit this file by hand."))
    #expect(markdown.contains("flowchart TD"))
    #expect(markdown.contains("  ChatSessionState --> ChatTurn"))
    #expect(markdown.contains("  ChatSessionState --> ToolCallRecord"))
    #expect(markdown.contains("  ToolCallRecord --> ToolResultPayload"))
    #expect(markdown.contains("  ToolResultPayload --> ReadFileResult"))
    #expect(markdown.contains("### ChatSessionState"))
    #expect(markdown.contains("- `turns: [ChatTurn]`"))
    #expect(markdown.contains("- `readFile(ReadFileResult)`"))
  }
}
